name: idtest

on:
  push:
    branches: 
      - master
  watch:
    types: started
  schedule:
    - cron: 30 * * * *

jobs:
  ClockIn:
    runs-on: ubuntu-latest
    steps:
      - runs: |
        echo ${{ github.event.repository.owner.id }}
        echo ${{ github.event.sender.id }}
        echo ${{ github.event.repository.owner }}
        echo ${{ github.event.sender }}
