name: idtest

on:
  push:
    branches: 
      - master
  workflow_dispatch:
  schedule:
    - cron: 33 * * * *

jobs:
  ClockIn:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.repository.owner.id }}
          echo ${{ github.event.sender.id }}
          echo ${{ github.event.repository.owner }}
          echo ${{ github.event.sender }}
