name: TestOutput

on:
  workflow_dispatch:
    inputs:
      cmdargs:
        description: 'Commandline Arguments'     
        required: false
        default: 'input' 
        type: string
  push:
      
jobs:
  RescueEventUpdate:
    runs-on: ubuntu-latest
    steps:
      - id: echoecho
        run: |
          echo "::set-output name=m1::111"
          echo "::set-output name=m3::333"
      - id: echoecho2
        run: |
          echo "${{ join([steps.echoecho.outputs.m1,steps.echoecho.outputs.m2,steps.echoecho.outputs.m3],'\n') }}"
