name: TestOutput

on:
  workflow_dispatch:
    inputs:
      cmdargs:
        description: 'Commandline Arguments'     
        required: false
        default: 'input' 
        type: string
  push:
    paths:
      - 'text.txt'
      
jobs:
  RescueEventUpdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.8'
      - id: echoecho
        run: |
          echo ${{ github.event }}
          echo ${{ inputs.cmdargs || 'default' }} ${{ github.event_name=='push' && 'push' || 'other' }}