name: TestOutput

on:
  workflow_dispatch:
    inputs:
      autocrlf:
        description: 'autocrlf'     
        required: false
        default: 'false' 
        type: string
      
jobs:
  RescueEventUpdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git config --global core.autocrlf ${{ inputs.autocrlf }}
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.8'
      - name: Create-CRLF
        run: python crlf.py
      - name: Commit-CRLF
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "CRLF Commit"
      - name: Create-LF
        run: python lf.py
      - name: Commit-LF
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "LF Commit"
